name: Build and Test

on:
  push:
    branches:
    - main

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Azure Functions Core Tools
      shell: pwsh
      run: |
        npm install -g azure-functions-core-tools@3 --unsafe-perm true

    - name: Setup .NET SDK 3.1 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Clear NuGet local cache
      shell: pwsh
      run: |
        dotnet nuget locals all --clear

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dir
        dotnet restore .

    - name: Build solution
      shell: pwsh
      run: |
        dir
        dotnet build . -c Debug -v minimal

    - name: Test function app (Windows)
      shell: pwsh
      run: |
        dir

        $rootDir = $pwd.Path
        $func = $(Get-Command func).Source.Replace(".ps1", ".cmd")

        cd ./src/FunctionApp
        # Start-Process -NoNewWindow "$func" start --verbose false
        Start-Process -NoNewWindow "$func" @("start","--verbose","false")
        Start-Sleep -s 60

        cd $rootDir/test/FunctionApp.Tests
        dotnet test . -c Debug
        cd $rootDir
